[project]
name = "turkish-kokoro"
version = "0.1.0"
description = "Training Kokoro-82M for Turkish TTS using StyleTTS2"
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.10, <3.14"
dependencies = [
    "datasets",
    "huggingface_hub",
    "loguru",
    "misaki[en]>=0.9.4",
    "numpy",
    "soundfile",
    "torch",
    "torchaudio",
    "torchcodec",
    "tqdm",
    "transformers",
]

[tool.uv]
find-links = ["https://download.pytorch.org/whl/cu128"]

[tool.uv.sources]
misaki = { git = "https://github.com/semidark/misaki.git", branch = "main" }
